sudo: required # ask for superuser
services:
  - docker # must be pre-installed
before_install:
  # tag only used in travis process
  - docker build -t eriddle2/docker-react -f Dockerfile.dev .
script:
  # travis assumes will exit when done (-- --coverage makes sure it does)
  - docker run -e CI=true eriddle2/docker-react npm run test -- --coverage

# http://dockerreact-env.k9zxfcrmqv.us-east-2.elasticbeanstalk.com/
deploy:
  provider: elasticbeanstalk # travis CI pre-configured for this and others
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-995932791916" # travis will zip up and copy to an S3 bucket (AWS Harddrive)
  bucket_path: "docker-react" # use app name when first setup
  on:
    branch: master # deploy when push code to master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
