version: "3"
services:
  web:
    build:
      context: . #pull files from current working directory
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app #current working directory outside container to /app folder in container
  tests: #second container responsible for running test; can't do standard input though
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] #override command
